### ISSUE TITLE
Failed to build with Python 3.8

### ISSUE THREAD

**Issue by PhuongNDVN** [LukasBommes/rtsp-streamsync#1]
First of all, thank you for sharing this, this helps me alot. When I try to build with python 3.6, it is built successfully but when I try to build it with python 3.8 (Ubuntu 20.04) it failed at the step: `cd /home/video_cap && python3 setup.py install`

**The error is:
src/py_video_cap.cpp:216:1: error: designator order for field ‘_typeobject::tp_getattr’ does not match declaration order in ‘PyTypeObject’ {aka ‘_typeobject’}
  216 | };
      | ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1** 

I think the definition of PyTypeObject changed compared to python 3.6. Could you update the source for python 3.8. Thanks!

Update: The solution is comment `.tp_print` in VideoCapType and StreamSynchronizerType structures

**Comment by LukasBommes** [comment]
Thanks for spotting this. I noted the build failure a while ago, but didn't have the time to look into it and fix it. I'll update the source as soon as I have some more time again...
